[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -D STACK_SIZE=512
    -D PRIORITY_SUPERVISION=3

lib_deps =
    nanopb/Nanopb@^0.4.8

[platformio]
src_dir = src
include_dir = include