/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_SAT_PB_H_INCLUDED
#define PB_SAT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _Command_Action {
    Command_Action_NOOP = 0,
    Command_Action_RESTART = 1,
    Command_Action_CHANGE_MODE = 2
} Command_Action;

/* Struct definitions */
typedef struct _Telemetry {
    uint32_t uptimeMs;
    float temperatureC;
    float batteryPercent;
    uint32_t mode;
    uint32_t status;
    uint32_t error;
} Telemetry;

typedef struct _Command {
    Command_Action action;
    uint32_t target_mode;
    uint32_t nonce;
} Command;

typedef PB_BYTES_ARRAY_T(128) SecureCommand_payload_t;
typedef PB_BYTES_ARRAY_T(32) SecureCommand_mac_t;

typedef struct _SecureCommand {
    SecureCommand_payload_t payload;
    SecureCommand_mac_t mac;
} SecureCommand;

/* Initializer values */
#define Telemetry_init_default                   {0, 0, 0, 0, 0, 0}
#define Command_init_default                     {Command_Action_NOOP, 0, 0}
#define SecureCommand_init_default               {{0, {0}}, {0, {0}}}
#define Telemetry_init_zero                      {0, 0, 0, 0, 0, 0}
#define Command_init_zero                        {Command_Action_NOOP, 0, 0}
#define SecureCommand_init_zero                  {{0, {0}}, {0, {0}}}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_uptimeMs_tag                   1
#define Telemetry_temperatureC_tag               2
#define Telemetry_batteryPercent_tag             3
#define Telemetry_mode_tag                       4
#define Telemetry_status_tag                     5
#define Telemetry_error_tag                      6
#define Command_action_tag                       1
#define Command_target_mode_tag                  2
#define Command_nonce_tag                        3
#define SecureCommand_payload_tag                1
#define SecureCommand_mac_tag                    2

/* Struct field encoding specification for nanopb */
#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   uptimeMs,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperatureC,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    batteryPercent,    3) \
X(a, STATIC,   SINGULAR, UINT32,   mode,              4) \
X(a, STATIC,   SINGULAR, UINT32,   status,            5) \
X(a, STATIC,   SINGULAR, UINT32,   error,             6)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL

#define Command_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    action,            1) \
X(a, STATIC,   SINGULAR, UINT32,   target_mode,       2) \
X(a, STATIC,   SINGULAR, UINT32,   nonce,             3)
#define Command_CALLBACK NULL
#define Command_DEFAULT NULL

#define SecureCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    payload,           1) \
X(a, STATIC,   SINGULAR, BYTES,    mac,               2)
#define SecureCommand_CALLBACK NULL
#define SecureCommand_DEFAULT NULL

extern const pb_msgdesc_t Telemetry_msg;
extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t SecureCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Telemetry_fields &Telemetry_msg
#define Command_fields &Command_msg
#define SecureCommand_fields &SecureCommand_msg

/* Maximum encoded size of messages (where known) */
#define Command_size                             14
#define SecureCommand_size                       165
#define Telemetry_size                           34

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
